### ISSUE TITLE
Exception when trying to open Cruise_finite1

### ISSUE THREAD

**Issue by leuschel** [hhu-stups/bmoth#85]
When I open Cruise_finite1.mch and then start model checking I get:
`
:run
May 31, 2017 1:13:35 PM com.google.common.eventbus.EventBus$LoggingHandler handleException
SEVERE: Exception thrown by subscriber method showException(de.bmoth.eventbus.ErrorEvent) on subscriber de.bmoth.app.AppController@1dbb273d when dispatching event: de.bmoth.eventbus.ErrorEvent@180d9bfd
java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-11
        at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:236)
        at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:423)
        at javafx.stage.Stage.<init>(Stage.java:241)
        at javafx.stage.Stage.<init>(Stage.java:227)
        at javafx.scene.control.HeavyweightDialog$1.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.HeavyweightDialog.<init>(HeavyweightDialog.java:52)
        at javafx.scene.control.Dialog.<init>(Dialog.java:263)
        at javafx.scene.control.Alert.<init>(Alert.java:245)
        at javafx.scene.control.Alert.<init>(Alert.java:223)
        at de.bmoth.app.ErrorAlert.<init>(ErrorAlert.java:9)
        at de.bmoth.app.AppController.showException(AppController.java:429)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
        at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
        at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
        at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
        at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
        at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
        at com.google.common.eventbus.EventBus.post(EventBus.java:217)
        at de.bmoth.exceptions.ParseErrorException.<init>(ParseErrorException.java:16)
        at de.bmoth.parser.ErrorListener.syntaxError(ErrorListener.java:15)
        at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:65)
        at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:564)
        at org.antlr.v4.runtime.DefaultErrorStrategy.reportUnwantedToken(DefaultErrorStrategy.java:375)
        at org.antlr.v4.runtime.DefaultErrorStrategy.sync(DefaultErrorStrategy.java:273)
        at de.bmoth.antlr.BMoThParser.machine_clause(BMoThParser.java:508)
        at de.bmoth.antlr.BMoThParser.parse_unit(BMoThParser.java:252)
        at de.bmoth.antlr.BMoThParser.start(BMoThParser.java:178)
        at de.bmoth.parser.Parser.parseMachine(Parser.java:41)
        at de.bmoth.parser.Parser.getMachineAsSemanticAst(Parser.java:68)
        at de.bmoth.modelchecker.ModelChecker.doModelCheck(ModelChecker.java:26)
        at de.bmoth.app.AppController$1.call(AppController.java:211)
        at de.bmoth.app.AppController$1.call(AppController.java:208)
        at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.lang.Thread.run(Thread.java:745)

`

**Comment by wysiib** [comment]
looks like a problem in the parser. i guess the machine uses something we do not support yet

**Comment by dohan** [comment]
The machine contains definitions which are currently not supported by the parser. Should the parser handle the definitions similar to ProB or as macros?

**Comment by wysiib** [comment]
no idea.... 
i guess macros are easier to implement?

**Comment by dohan** [comment]
I have already implemented the "ProB way" to handle definitions on a feature branch of the B parser (without using a pre parser!). I will try to migrate this code. Definition calls will be replaced before the type checking phase to handle e.g. the following example:
PROPERTIES foo(2,1) = 1 & foo({2,1},{1}) = {2}
DEFINITIONS foo(a,b) == a - b
Then the backend does not have to care about definitions at all.

**Comment by wysiib** [comment]
I think parser support for becomes-such-that is still missing?
E.g. in SomeVar :: BOOL

**Comment by wysiib** [comment]
IF ... THEN ... ELSE can not be parsed at the moment....

**Comment by dohan** [comment]
Cruise_finite1 is now supported by the model checker. However, only 9 states are explored (no invariant violation) but it should be 1360. I think we need more tests for the class MachineToZ3Translator.

**Comment by wysiib** [comment]
how did you translate the if-then-else?

**Comment by dohan** [comment]
IF P THEN S ELSE E END to (P & S') or (not(P) & E')

**Comment by dohan** [comment]
The translation of IF-THEN-ELSE seems to be sound (ensured by tests).
There is one problem in the ModelChecker class:
`Set<Model> models = finder.findSolutions(initialValueConstraint,              BMothPreferences.getIntPreference(BMothPreferences.IntPreference.MAX_INITIAL_STATE));`
The number of distinct initial states does not correspond to the number of models found. For this example, there should be 4 initial states. However, 11 models were found (using my preferences) which cover only 3 of 4 initial states. The number of models results from an existential quantification in initialisation clause.
All initial states can be found by increasing the values of MAX_INITIAL_STATE and MAX_TRANSITIONS. However, the model checker now reports "check-sat = unknown, reason: timeout" for this example. We should handle each operation separately in model checker in order to provide appropriate error message in case of timeouts.
